[build-system]
requires = []
build-backend = ""

[tool.setuptools]
packages = []

[project]
name = "genhack4-hackathon-vertex"
version = "1.0.0"
requires-python = ">=3.11,<3.12"
description = "GenHack Climate API - Backend for downscaling climate data"
